blank_issues_enabled: false
contact_links:
  - name: Zopen Community Discussions
    url: https://github.com/IBM/zopen-community/discussions
    about: Use this discussion board for sharing ideas related to the zopen community.
