name: Create New Port Repository

on:
  issues:
    types: [labeled]

jobs:

  create-repo:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Extract Port Name
      run: |
        echo "PORT_NAME=$(echo "${GITHUB_EVENT_ISSUE_TITLE}" | cut -d: -f2- | tr -d ' ' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      env:
        GITHUB_EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        
    - name: Check if Repository Exists
      env:
        ORGANIZATION: zopencommunity
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PORT_NAME: ${{ env.PORT_NAME }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
      run: |
        REPO_NAME="${PORT_NAME}port"
        
        if gh repo view "$ORGANIZATION/$REPO_NAME" &> /dev/null; then
          echo "Repository '$ORGANIZATION/$REPO_NAME' already exists."
          exit 1
        else
          echo "Repository '$ORGANIZATION/$REPO_NAME' does not exist. Proceeding to create it."
          gh repo create "$ORGANIZATION/$REPO_NAME" --public
          
          # Assign the issue creator as the admin
          gh repo access add-user "$ORGANIZATION/$REPO_NAME" ${{ github.event.issue.user.login }} --admin

          # Post a comment on the issue
          gh issue comment "$ISSUE_NUMBER" --repo "$ORGANIZATION/meta" --token "$GH_TOKEN" --body "Repository created: $ORGANIZATION/$REPO_NAME"
        fi
