name: Create New Port Repository

on:
  issues:
    types: [labeled]

jobs:

  create-repo:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Extract Port Name
      run: |
        echo "PORT_NAME=$(echo "${GITHUB_EVENT_ISSUE_TITLE}" | cut -d: -f2- | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      env:
        GITHUB_EVENT_ISSUE_TITLE: ${{ github.event.issue.title }}
        
    - name: Check if Repository Exists
      env:
        ORGANIZATION: IgorTodorovskiIBM
        PORT_NAME: ${{ env.PORT_NAME }}
      run: |
        REPO_NAME="${PORT_NAME}-port"
        
        # Check if the repository already exists
        if gh repo view "$ORGANIZATION/$REPO_NAME" &> /dev/null; then
          echo "Repository '$ORGANIZATION/$REPO_NAME' already exists."
          exit 1
        else
          echo "Repository '$ORGANIZATION/$REPO_NAME' does not exist. Proceeding to create it."
          gh repo create "$ORGANIZATION/$REPO_NAME" --source=. --private --confirm
          
          # Assign the issue creator as the admin
          gh repo access add-user "$ORGANIZATION/$REPO_NAME" ${{ github.event.issue.user.login }} --admin
        fi
