name: Build and Test

on:
  issue_comment:
    types:
      - created
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'cicd*.groovy'
      - '**/LICENSE'
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-and-test:
    if: (github.event.issue.pull_request && contains(github.event.comment.body, '/run tests')) || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_target'
    uses: ZOSOpenTools/meta/.github/workflows/build_and_test.yml@main
    secrets: inherit
    with:
      repo: 'https://github.com/ZOSOpenTools/metaport.git'
      use_prbranch_as_build_branch: true
