name: Build and Test

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened 
  workflow_dispatch:

jobs:
  build-meta-on-jenkins:
    if: github.event.issue.pull_request || contains(github.event.comment.body, '/run tests') || github.event_name == 'workflow_dispatch'
    uses: ZOSOpenTools/meta/.github/workflows/build_and_test.yml@main
    with:
      repo: 'https://github.com/ZOSOpenTools/metaport.git'
      use_prbranch_as_build_branch: true
    secrets: inherit
