name: Test meta port

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - opened 
  workflow_dispatch:

jobs:
  build-meta-on-jenkins:
    uses: ZOSOpenTools/meta/.github/workflows/build_and_test.yml@main
    with:
      repo: 'https://github.com/ZOSOpenTools/metaport.git'
      use_prbranch_as_build_branch: true
    secrets: inherit
